# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x = np.random.randn(8)

In [7]:
y = np.random.randn(8)

In [8]:
x

array([-0.7877452 ,  0.8270847 ,  1.3876452 , -0.59058076,  1.07233779,
       -0.66061861,  0.50015996, -0.52837269])

In [9]:
y

array([-1.01620293, -0.19127939, -0.75033019,  0.96826666, -0.10772097,
       -0.34216782, -1.18167103,  0.78038833])

In [10]:
np.maximum(x, y)

array([-0.7877452 ,  0.8270847 ,  1.3876452 ,  0.96826666,  1.07233779,
       -0.34216782,  0.50015996,  0.78038833])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = np.random.randn(7) * 5

In [13]:
arr

array([ 2.48051521,  5.00433785,  6.34852363, -7.09696517, -6.33750594,
       11.99924461,  2.55273115])

In [14]:
remainder, whole_part = np.modf(arr)

In [15]:
remainder

array([ 0.48051521,  0.00433785,  0.34852363, -0.09696517, -0.33750594,
        0.99924461,  0.55273115])

In [16]:
whole_part

array([ 2.,  5.,  6., -7., -6., 11.,  2.])

In [17]:
arr

array([ 2.48051521,  5.00433785,  6.34852363, -7.09696517, -6.33750594,
       11.99924461,  2.55273115])

In [18]:
np.sqrt(arr)

<ipython-input-18-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.57496515, 2.23703774, 2.51962768,        nan,        nan,
       3.46399258, 1.59772687])

In [19]:
np.sqrt(arr, arr)

<ipython-input-19-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.57496515, 2.23703774, 2.51962768,        nan,        nan,
       3.46399258, 1.59772687])

In [20]:
arr

array([1.57496515, 2.23703774, 2.51962768,        nan,        nan,
       3.46399258, 1.59772687])