# Arithmetic with Numpy Arrays

In [1]:
import numpy as np

In [3]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [4]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2> arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing & Slicing

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[1] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [12]:
arr_slice[:] = 64

In [13]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [14]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
arr2d[2]

array([7, 8, 9])

In [16]:
arr2d[1]

array([4, 5, 6])

In [17]:
arr2d[0][2]

3

In [18]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [19]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
old_values = arr3d[0].copy()

In [22]:
arr3d[0] = 42

In [23]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0] = old_values

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1, 0]

array([7, 8, 9])

In [28]:
x = arr3d[1]

In [30]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [31]:
x[0]

array([7, 8, 9])

In [32]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [40]:
arr2d[1, :2]

array([4, 5])

In [41]:
arr2d[:2, 2]

array([3, 6])

In [52]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [89]:
arr2d[:, 1:2]

array([[2],
       [5],
       [8]])

In [112]:
arr2d[:, 2:3]

array([[3],
       [6],
       [9]])

In [113]:
arr2d[:2, 1:] = 0

In [114]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [119]:
arr2d[2]

array([7, 8, 9])

In [120]:
arr2d[2, :2]

array([7, 8])

In [122]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [124]:
arr2d[1:2, :2]

array([[4, 0]])

In [125]:
arr2d[:, :2]

array([[1, 0],
       [4, 0],
       [7, 8]])

In [128]:
arr2d[:2, 1:]

array([[0, 0],
       [0, 0]])

In [127]:
arr2d[:2, 1:]

array([[0, 0],
       [0, 0]])