# Boolean Indexing

In [1]:
import numpy as np

In [10]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [11]:
data = np.random.randn(7, 4)

In [12]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [13]:
data

array([[ 0.36750838, -0.29709266,  2.10256503, -0.80315117],
       [-0.7758899 ,  0.07596581, -2.43154064,  1.20124417],
       [ 1.67265828,  0.72589438, -0.23254826,  0.14803898],
       [-0.68015659, -0.73348675, -1.63367669, -1.32195378],
       [ 2.26643329, -0.40334728, -0.10738902, -0.57308212],
       [ 1.54758233,  1.18569484, -1.0139459 , -0.3781764 ],
       [ 1.7739519 , -0.54749005,  0.79953545,  1.2737078 ]])

In [14]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [15]:
data[names == 'Bob']

array([[ 0.36750838, -0.29709266,  2.10256503, -0.80315117],
       [-0.68015659, -0.73348675, -1.63367669, -1.32195378]])

In [17]:
data[names =='Bob, 2']

array([], shape=(0, 4), dtype=float64)

In [18]:
data[names =='Bob', 2:]

array([[ 2.10256503, -0.80315117],
       [-1.63367669, -1.32195378]])

In [19]:
data[names == 'Bob', 3]

array([-0.80315117, -1.32195378])

In [20]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [21]:
data[~(names == 'Bob')]

array([[-0.7758899 ,  0.07596581, -2.43154064,  1.20124417],
       [ 1.67265828,  0.72589438, -0.23254826,  0.14803898],
       [ 2.26643329, -0.40334728, -0.10738902, -0.57308212],
       [ 1.54758233,  1.18569484, -1.0139459 , -0.3781764 ],
       [ 1.7739519 , -0.54749005,  0.79953545,  1.2737078 ]])

In [22]:
cond = names == 'Bob'

In [23]:
data[~cond]

array([[-0.7758899 ,  0.07596581, -2.43154064,  1.20124417],
       [ 1.67265828,  0.72589438, -0.23254826,  0.14803898],
       [ 2.26643329, -0.40334728, -0.10738902, -0.57308212],
       [ 1.54758233,  1.18569484, -1.0139459 , -0.3781764 ],
       [ 1.7739519 , -0.54749005,  0.79953545,  1.2737078 ]])

In [24]:
mask = (names == 'Bob') | (names == 'Will')

In [25]:
mask

array([ True, False,  True,  True,  True, False, False])

In [26]:
data[mask]

array([[ 0.36750838, -0.29709266,  2.10256503, -0.80315117],
       [ 1.67265828,  0.72589438, -0.23254826,  0.14803898],
       [-0.68015659, -0.73348675, -1.63367669, -1.32195378],
       [ 2.26643329, -0.40334728, -0.10738902, -0.57308212]])

In [27]:
data[data <0] = 0

In [28]:
data

array([[0.36750838, 0.        , 2.10256503, 0.        ],
       [0.        , 0.07596581, 0.        , 1.20124417],
       [1.67265828, 0.72589438, 0.        , 0.14803898],
       [0.        , 0.        , 0.        , 0.        ],
       [2.26643329, 0.        , 0.        , 0.        ],
       [1.54758233, 1.18569484, 0.        , 0.        ],
       [1.7739519 , 0.        , 0.79953545, 1.2737078 ]])

In [29]:
data[names != 'Joe'] = 7

In [30]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.07596581, 0.        , 1.20124417],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.54758233, 1.18569484, 0.        , 0.        ],
       [1.7739519 , 0.        , 0.79953545, 1.2737078 ]])

# Fancy Indexing

In [33]:
arr = np.empty((8, 4))

In [35]:
for i in range(8):
    arr[i] = i

In [36]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [37]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [38]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [42]:
arr = np.arange(32).reshape((4, 8))

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [44]:
arr = np.arange(32).reshape((8, 4))

In [45]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [47]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays And Swapping Axes

In [48]:
arr =np.arange(15).reshape((3,5))

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [51]:
arr =np.random.randn(6, 3)

In [52]:
arr

array([[ 0.77650824, -0.90324271,  0.75999206],
       [ 0.09403574, -0.32846485, -0.84448234],
       [ 1.23797903,  1.55953973, -0.39662538],
       [ 2.01877476,  3.38920942, -0.68038154],
       [ 1.34390344, -1.78807732, -0.47222412],
       [ 0.53772436, -1.53019046,  1.92218407]])

In [53]:
np.dot(arr.T, arr)

array([[ 8.31507533,  4.8146411 , -0.95484082],
       [ 4.8146411 , 20.38134458, -5.43051757],
       [-0.95484082, -5.43051757,  5.82875629]])

In [56]:
arr = np.arange(16).reshape((2, 2, 4))

In [57]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [58]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [59]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [60]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])