In [1]:
import numpy as np

In [5]:
arr = np.random.randn(5, 4)

In [6]:
arr

array([[-0.16083952,  0.03127962, -1.38533143, -1.20340295],
       [ 0.39554702,  1.4012311 ,  0.36684999,  0.21329655],
       [-1.06000447, -0.01926601,  1.8617095 ,  1.34682734],
       [ 1.18557091,  0.71152055, -0.47593936, -0.35245088],
       [-0.68507704,  0.95516552,  0.33674271, -0.02914672]])

In [7]:
arr.mean()

0.17171412128971594

In [8]:
np.mean(arr)

0.17171412128971594

In [9]:
arr.sum()

3.434282425794319

In [10]:
arr.mean(axis=1)

array([-0.67957357,  0.59423117,  0.53231659,  0.26717531,  0.14442111])

In [11]:
arr.sum(axis=0)

array([-0.3248031 ,  3.07993078,  0.70403142, -0.02487667])

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [14]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [15]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [17]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

# Method for Boolean Arrays

In [18]:
arr = np.random.randn(100)

In [19]:
(arr > 0).sum()

58

In [20]:
bools = np.array([False, False, True, False])

In [21]:
bools.any()

True

In [22]:
bools.all()

False

# Sorting

In [23]:
arr =np.random.randn(6)

In [24]:
arr

array([-1.47953176,  0.97364665, -1.23585441, -0.82833764, -0.28965462,
       -1.51770688])

In [25]:
arr.sort()

In [26]:
arr

array([-1.51770688, -1.47953176, -1.23585441, -0.82833764, -0.28965462,
        0.97364665])

In [27]:
arr = np.random.randn(5, 3)

In [28]:
arr

array([[-0.51660841,  1.27787334,  0.26466772],
       [ 0.62920475,  0.18594964, -0.69072031],
       [ 0.67244165, -0.36558724, -1.28058904],
       [-0.55320288,  0.14973759,  0.18926918],
       [-0.28171547, -1.24428279, -0.93535454]])

In [29]:
arr.sort(1)

In [30]:
arr

array([[-0.51660841,  0.26466772,  1.27787334],
       [-0.69072031,  0.18594964,  0.62920475],
       [-1.28058904, -0.36558724,  0.67244165],
       [-0.55320288,  0.14973759,  0.18926918],
       [-1.24428279, -0.93535454, -0.28171547]])

In [31]:
large_arr = np.random.randn(1000)

In [32]:
large_arr.sort()

In [34]:
large_arr[int(0.05 * len(large_arr))]

-1.4603656970152923

# Unique & Other Set Logic

In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [39]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [40]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [41]:
np.unique(ints)

array([1, 2, 3, 4])

In [42]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [43]:
values = np.array([6,0,0,3,2,5,6])

In [44]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])